# Generated by Django 4.2.4 on 2023-09-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_persentage', models.IntegerField(default=0)),
                ('increase_persentage', models.IntegerField(default=0)),
                ('increase_days', models.IntegerField(default=0)),
            ],
        ),
    ]
